### ISSUE TITLE
media-video/bcwc_pcie fails to compile with 4.9.203 (and probably other versions as well)

### ISSUE THREAD

**Issue by simonvanderveldt** [toaster/gentoo-overlay#12]
Hi Tilo, it seems like for the bcwc_pcie module we should be using the `master` branch instead of the `mainline` branch, see https://github.com/patjak/bcwc_pcie/issues/193#issuecomment-563380519
I get the compilation error from that linked issue on 4.9.203 with the current ebuild which uses the `mainline` branch.

**Comment by cjosephson** [comment]
Seconding this issue

**Comment by toaster** [comment]
Hi there, sorry for the delay. Currently I don't have Gentoo on a Mac therefore I don't do anything on these ebuilds. Luckily @cjosephson took care of it. So this issue should be fixed with #14.
